//LOCALHOST 
### Get all users
GET http://localhost:3000/contacts


### Get contact by id
GET http://localhost:3000/contacts/67cca101ac48fd568c391abc

### Create contact
POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
   "firstName": "testFirst1",
    "lastName": "testLast1",
    "email": "test@example.com1",
    "favoriteColor": "testColor1",
    "birthday": "testBirthday1"
}

### PUT contact
PUT http://localhost:3000/contacts/67d9aedfdf5540ddbaf44e4c HTTP/1.1
Content-Type: application/json

{
    "firstName": "Miriam",
    "lastName": "Motrtazavi",
    "email": "test@example.com",
    "favoriteColor": "blue",
    "birthday": "Aguest, 15 1997"
}

### DELETE
DELETE http://localhost:3000/contacts/67d9aedfdf5540ddbaf44e4c HTTP/1.1